name: wiwa_app
description: Social Media with Music Streaming and E-Commerce support.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.1.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"
  # sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  dartz: ^0.9.2
  get_it: ^5.0.6
  freezed_annotation: ^0.12.0
  # flutter_link_preview: ^1.5.6
  any_link_preview:
  # ^1.0.8
  cached_network_image: ^3.1.0
  provider: ^5.0.0
  firebase_auth: ^2.0.0
  firebase_database:
  firebase_analytics:
  cloud_firestore: ^2.3.0
  firebase_storage:
  firebase_core: ^1.3.0
  equatable: ^2.0.0
  http: ^0.13.3
  image_picker: ^0.8.2
  package_info: ^0.4.1
  shared_preferences: ^0.5.1+2
  firebase_messaging: ^10.0.3
  # google_sign_in: "^4.5.1"
  google_sign_in: ^5.0.7
  intl: ^0.17.0
  url_launcher:
  share: ^2.0.4
  google_fonts: ^2.1.0
  firebase_remote_config: ^0.10.0+2
  firebase_dynamic_links: ^2.0.6
  qr_code_scanner: ^0.3.5
  qr_flutter: ^3.2.0
  rxdart: ^0.27.1
  flutter_login_facebook: ^1.1.0
  # twitter_login: ^4.0.1
  flutter_twitter:
  video_compress: ^3.1.0
  # video_player: ^2.1.14
  chewie: ^1.2.2
  internet_connection_checker: ^0.0.1+2
  google_mobile_ads: ^0.13.4

  # Extra Plugins for Ahia
  # dots_indicator: ^1.2.0
  carousel_slider: ^4.0.0
  expandable_text: ^2.2.0
  flutter_easyloading: ^3.0.0
  toggle_bar: ^1.0.0
  dotted_border: ^2.0.0+1
  chips_choice: ^2.0.1
  search_page: ^2.0.0+1
  persistent_bottom_nav_bar: ^4.0.2

  # Music
  file_picker: ^4.0.0
  # audioplayers:
  path_provider: ^2.0.2
  just_audio: ^0.9.7
  # ^0.6.15+1
  audio_service: ^0.17.1
  miniplayer: ^1.0.0+2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # supabase: ^0.2.7
  # flip_card: ^0.5.0
  # material_design_icons_flutter: ^5.0.5955-rc.1
  # material_floating_search_bar: ^0.3.4
  # palette_generator: ^0.3.1
  # dart_des: ^1.0.0
  # flutter_archive: ^4.0.1
  # flutter_displaymode: ^0.3.2
  # app_links: ^2.2.0
  # on_audio_query: ^2.5.0
  # audiotagger: ^2.2.1

  # Wiwa Icon
  # flutter_launcher_icons:
  # path: ../..

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

  # build_runner: ^1.10.11
  # json_annotation: ^3.1.1
  # json_serializable: ^3.5.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/wiwaicon.png"
  image_path_android: "assets/wiwaicon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/icon-48.png
    - assets/images/icon-480.png
    - assets/images/icon-400.png
    - assets/images/qr.png
    - assets/images/bulb.png
    - assets/images/google_logo.png
    - assets/images/twitter_logo.png
    - assets/images/facebook_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
    # - family: AssetAudioPlayer
    #   fonts:
    #     - asset: assets/fonts/AssetAudioPlayer.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
